# Generated by Django 4.0 on 2021-12-16 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rooms'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rooms',
            new_name='Room',
        ),
    ]
