# Generated by Django 4.0 on 2021-12-16 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tag'),
        ),
    ]
