# Generated by Django 4.0 on 2021-12-18 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_user_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='host',
            new_name='author',
        ),
    ]
