# Generated by Django 4.0 on 2021-12-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_host_answer_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='interest',
            field=models.ManyToManyField(null=True, to='api.Tag'),
        ),
    ]
