# Generated by Django 4.0 on 2021-12-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_tag_description_user_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='interest',
            field=models.ManyToManyField(to='api.Tag'),
        ),
    ]
