# Generated by Django 4.0 on 2021-12-19 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_user_interest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='interest',
            new_name='interests',
        ),
    ]
