# Generated by Django 4.0 on 2021-12-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='https://res.cloudinary.com/wizzle3d/image/upload/v1637699597/vaito/default_ni4q8g.jpg', max_length=150),
        ),
    ]
