# Generated by Django 4.0 on 2021-12-25 13:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_notification_notificationchange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='question',
        ),
        migrations.AddField(
            model_name='notification',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
