# Generated by Django 4.0 on 2021-12-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_notification_question_notification_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='notification',
            name='receiverID',
            field=models.IntegerField(null=True),
        ),
    ]
