# Generated by Django 4.0 on 2021-12-26 08:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_notification_user_notification_receiverid'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionID', models.IntegerField(null=True)),
                ('answerID', models.IntegerField(null=True)),
                ('commentID', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='notificationchange',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificationchange',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notificationchange',
            name='notification_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change', to='api.notificationobject'),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
