# Generated by Django 4.0 on 2021-12-26 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_notificationobject_notificationchange_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiverID', models.IntegerField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='notificationobject',
            old_name='answerID',
            new_name='entityID',
        ),
        migrations.RemoveField(
            model_name='notificationobject',
            name='commentID',
        ),
        migrations.AddField(
            model_name='notificationchange',
            name='actionID',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='notificationchange',
            name='action_type',
            field=models.CharField(default='comment', max_length=30),
        ),
        migrations.AddField(
            model_name='notificationobject',
            name='entity_type',
            field=models.CharField(default='question', max_length=30),
        ),
        migrations.AlterField(
            model_name='notificationchange',
            name='notification_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='change', to='api.notificationobject'),
        ),
        migrations.AddField(
            model_name='notificationobject',
            name='notification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obj', to='api.notification'),
        ),
    ]
