# Generated by Django 4.0 on 2021-12-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_remove_notificationobject_entityid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='unseen_count',
            field=models.IntegerField(default=0),
        ),
    ]
