# Generated by Django 4.0 on 2021-12-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_notification_unseen_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationobject',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
